### PR TITLE
prefer https

### PR DESCRIPTION
**Pull request by bernd289**

### CODE REVIEW

**Comment by lewisje** [comment]
While you're at it, it might be better to prefer rawgit.com over raw.githubusercontent.com (to reduce bandwidth on GitHub's servers).

**Comment by bernd289** [comment]
http://rawgit.com/faq - "Requests to cdn.rawgit.com are routed through MaxCDN's super fast content delivery network, and are **cached permanently**" - means no updated filter lists, right? not really what we want... ;)

**Comment by lewisje** [comment]
I guess you mean client-side, because I know that it gets updated on RawGit when I update a file on GitHub.

**Comment by chrisaljoudi** [comment]
@lewisje @b3rnd 

RawGit provides two URLs:

rawgit urls

The CDN URL is indeed cached permanently ([tested here](https://github.com/chrisaljoudi/HandWave/commit/5ccd045b271838fcbece1e495643e8bd0f069481)), but the _other_ one (the non-CDN one) isn't cached permanently and will occasionally issue more requests to GitHub for updates.

Given those circumstances, it'd have to be either `rawgit.com` or `raw.githubusercontent.com` (not `cdn.rawgit.com`).

However, the only advantage to using `rawgit.com` is the `Content-type` headers being appropriate (plus a small amount of short-term caching). Other than that, it hits **both** `rawgit.com` and `raw.githubusercontent.com` (which is arguably worse than just hitting the latter).

So it seems like `raw.githubusercontent.com` is the only reasonable answer for lists hosted exclusively on GitHub.

**Comment by jvoisin** [comment]
Is there something to correct/fix/improve to get this pull-request merged?

**Pull request merged**
