### PR TITLE
Fix YouTube ClickToPlugin conflict

### LINKED ISSUE #615: [Safari] uBlock 0.8.6.0 Breaks Other Extension - ClickToPlugin
The latest version breaks ClickToPlugin, prior that both works perfectly together.

### PR DESCRIPTION
**Pull request by chrisaljoudi**
Resolves #615

### CODE REVIEW

**Comment by d4v1dv00** [comment]
may I ask when will this fix being released as beta?

**Comment by gorhill** [comment]
I will do it now, after I import changes from Crowdin, if any.

**Comment by locusathome** [comment]
@chrisaljoudi I am sorry but there still is a bug somewhere with µBlock 0.8.6.0 and ClickToPlugin on youtube.com.
After clean install µBlock 0.8.6.0 and update all (default) filters, cleaning all history, website data, cookies etc, restarting Safari I am able to watch a youtube video.

Reloading the same youtube page and I get 'video unavailable update to latest flash or update to latest quicktime'.

Cleaning up all Safari data, restart to the same page and I am able to watch the video, reload the same page and I get the error 'video unavailable update to latest flash or update to latest quicktime'.

So after cleaning up I am able to watch a video, reloading the same page and it is error.

**Comment by chrisaljoudi** [comment]
@locusathome new 0.8.6.0 beta released (includes more fixes to YouTube) — see if that fixes the issue.

**Comment by locusathome** [comment]
@chrisaljoudi Nope, no change.

If I disable for this site on youtube, I get the normal behaviour of ClickToPlugin and I am able to watch HTML5 video.

This is on OS X 10.10.2, Safari 8.0.3, ClickToPlugin 3.0 and µBlock 0.8.6.0 beta through extension update.

**Comment by chrisaljoudi** [comment]
@locusathome commit acf434f691db90a9a072fa2667896c5fa5479854 fixes this. Sorry about that.

**Comment by locusathome** [comment]
@chrisaljoudi It is okay now, nice job

**Comment by locusathome** [comment]
@chrisaljoudi Please don't be sorry for that. I am deeply thrilled that there are people like you and @gorhill and @Deathamns who develop extension(s) for Safari (and other browsers) which greatly enhance the web and that for free!

So thank you!

**Comment by ErikSwan** [comment]
Thanks for fixing this guys!

**Pull request merged**
