### PR TITLE
Arabic Translation

### PR DESCRIPTION
**Pull request by xPoison**
Hey so i decided to fork and translate my beloved ad blocker to my own language which is Arabic, i have finished about 95% and will be finishing the rest in the soon future.(Very Soon)

http://i.imgur.com/iXLstbu.png

http://i.imgur.com/0ogTb93.png

Forget about the version i was just playing with it on my own lol.

### CODE REVIEW

**Comment by gorhill** [comment]
OK, I will look at this tomorrow. Actually if you could upload your `messages.json` to [uBlock on Crowdin](https://crowdin.com/project/ublock/ar)  that would be better, this simplifies my work and future maintenance. Thanks for your work.

Btw, I looked at the screenshots, I thought Arabic was a right-to-left language... Was the browser running natively in Arabic or you were just testing Arabic while running the browser natively in some left-to-right language (Français?) ?

**Comment by xPoison** [comment]
Hello thanks for replying mmm i really would like but unfortunately never used the site i use transifex and github that's all lol but if you want me to do ill gladly do it tomorrow. 

Yes Arabic is right to left but its okay if its from left to right i can read and anybody can read it.
No the browser which was chrome latest stable build was in English not french or Arabic i was simply testing my translation to see if its okay that's it.

But Remember its not completely finished probably 98% finished so i need to finish it, ill be going to sleep now when i wake up ill probably finish it and i forgot if you need anything to translate into arabic i am gladly to do it.

Your welcome see you tomorrow.

**Comment by gorhill** [comment]
> when i wake up ill probably finish it and i forgot if you need anything to translate into arabic i am gladly to do it.

Ok so I will wait for the remaining work before updating the extension in Chrome store. For Opera store they require the [description](https://github.com/gorhill/uBlock/tree/master/dist/description) to also be available in the translated language though before I can submit a new version with support for Arabic.

**Comment by xPoison** [comment]
Ok, i just woke up  i will finish the remaining translation and will translate the description in the next few hours. Thank you.

**Pull request merged**
