### PR TITLE
Losslessly optimize images

### PR DESCRIPTION
**Pull request by CoolOppo**
I reduced the size of all the images changed in this commit with [OptiPNG](http://optipng.sourceforge.net) and [Gifsicle](http://www.lcdf.org/gifsicle).

### CODE REVIEW

**Comment by lewisje** [comment]
If you want to be super-optimized, try TruePNG (to optimize palette in transparent areas) followed by PNGOUT, AdvPNG, AdvDef, DeflOpt, Defluff, and DeflOpt again...or something like that.

As for GIFs, I don't know any other lossless optimizer, but I know for JPGs there is JPEGOptim (I haven't checked whether the repo even has any JPGs).

I might try something like that once this pull request is either merged or blocked.

**Comment by CoolOppo** [comment]
@lewisje The best way to optimize JPEGs losslessly is mozjpeg. The absolute best for PNGs is zopflipng, without a doubt, but it's pretty slow.

**Comment by lewisje** [comment]
I just found pre-built Win32 binaries of mozjpeg, which are very helpful: http://mozjpeg.codelove.de/binaries.html

**Comment by CoolOppo** [comment]
It's actually really easy to build mozjpeg on Windows. Just follow the
instructions Mozilla provides (with CMake and all that). I can give you a
build for the latest version if you want; I'm going to actually build it
right now.

**Comment by CoolOppo** [comment]
@lewisje I just built everything with GCC 5.1.1 ([from here](https://sourceforge.net/projects/mingw-w64/files/Toolchains%20targetting%20Win64/Personal%20Builds/dongsheng-daily/5.x/gcc-5-win64_5.1.1-20150425.7z/download)) on Windows. Here's the build:

https://www.dropbox.com/s/80p9ggldaj7acvs/WjEbo-1430449118.876.7z?dl=1

**Comment by lewisje** [comment]
Since this PR convo, I have found FileOptimizer, which bundles the utilities discussed here, and more things, like Leanify: http://nikkhokkho.sourceforge.net/static.php?page=FileOptimizer

**Comment by chrisaljoudi** [comment]
Also check out [ImageOptim](https://imageoptim.com).

**Comment by lewisje** [comment]
I've known about that and [PNGGauntlet](http://pnggauntlet.com/) and [Trimage](http://trimage.org/) for a long time (I heard about PNGGauntlet first, and its homepage recommended ImageOptim for OS X and Trimage for Linux), but FileOptimizer is newer and more comprehensive; however, there isn't an obvious way to get FileOptimizer to run on OS X, while FileOptimizer does run under Wine for Linux.

**Pull request closed without merging**
