### PR TITLE
Candidate for fix for #1140

### PR DESCRIPTION
**Pull request by AlexVallat**
As described in https://github.com/gorhill/uBlock/issues/1140#issuecomment-88398777, this is a work around for Firefox sending `document-element-inserted` before `nsIWebProgressListener.onLocationChange`. It would, however, mean that we will usually get two location changes for the same page.

### CODE REVIEW

**Comment by gorhill** [comment]
@AlexVallat 

Is that you: https://addons.mozilla.org/en-Us/firefox/user/AlexV/ ?

**Comment by AlexVallat** [comment]
Yes, that's me, why?

**Comment by gorhill** [comment]
Do you want to take over the add-on on Firefox?

**Comment by AlexVallat** [comment]
Is @Deathamns leaving? That's bad news! I've just noticed you transferred the project to @chrisaljoudi too, wow.

OK, well, I'll certainly do my best to maintain the Firefox bits, although my time becomes more limited after the Easter holidays finish.

How do you want to handle the AMO listing - do you want me to maintain that, or is @chrisaljoudi already doing that as part of the build process?

**Comment by gorhill** [comment]
> do you want me to maintain that

That would be best, as you worked on the Firefox-specific code. What e-mail do I use to add you as a manager?

**Comment by AlexVallat** [comment]
My AMO account email is -edit removed-, thanks

@chrisaljoudi: When you get a few minutes, we should talk about build and deployment processes, and see how much automation can be achieved. Also, what sort of dev release / blessed release system you want to use - once it's fully reviewed we can push out a faster release developer channel as well as reviewed full releases.

**Comment by AlexVallat** [comment]
On reflection, this is not really the right place to discuss this, so I've created an issue for it: #1166 

Returning briefly to topic - If @Deathamns is no longer participating, then I guess code review for this is up to @chrisaljoudi now, perhaps when things calm down a bit!

**Pull request merged**
