### PR TITLE
Safari: more compatible build, better popover sizing

### PR DESCRIPTION
**Pull request by chrisaljoudi**

### CODE REVIEW

**Comment by chrisaljoudi** [comment]
@gorhill hmm, interesting. I'll have to look at the Firefox code more.

I've added `vadi-popup.js` for Safari and moved that popup-specific stuff out of `vapi-common.js`. Also, the mini library for size-change detection is now non-minified.

**Comment by Deathamns** [comment]
@chrisaljoudi On the Firefox [branch](https://github.com/Deathamns/uBlock/tree/ports/xpi/) many changes were added to the Safari code too, which are not pushed to the master here, but they're more up to date. For example the compatibility with Python2.

The idea behind using mutation observers was to achieve transparent behavior, since no extra elements will be added to the popup. As a result it removes the chance of interfering with the main application in any way.

**Comment by gorhill** [comment]
> no extra elements will be added to the popup

I realized this afterward reading the code, and really I am not sure what to think, so I leave it to the platform-specific code to decide. Your mutation observer is almost a noop, so I don't really fear an overhead problem -- despite the popup UI removing/adding a node on mouse move.

**Comment by chrisaljoudi** [comment]
@gorhill @Deathamns sure, I get the logic. 

It's up to you, I guess. Sure, the current way of listening adds two invisible children (which should also have no effect on the layout) — but it only fires on size changes (the mutation observer will fire on modifications to children that may not have effect on size). 

In any case, it's up to you. 

It's worth mentioning that if we do go back to mutation observers, we should probably still keep the changes to the size calculation from this pull (not hard coding the magic constants that are the initial size).

**Comment by gorhill** [comment]
@chrisaljoudi as said I really don't have an opinion. On one side there is the extra overhead of mutation observer firing a lot compare to scroll event, on the other there is tampering with the popup UI which could be a problem in the future if adding some CSS rules which affect the added nodes. I just can't decide what is best. I will leave it to you two to decide.

**Pull request merged**
