### PR TITLE
New icons

### PR DESCRIPTION
**Pull request by CoolOppo**
I spent some time remaking all of the icons. The main reason was that the browser action icon didn't look too great, but I decided to just change every icon since there was (a little) room for improvement. The most important change is that the icons are properly hinted and anti-aliased, so they don't appear blurry any more. This is especially noticeable in the 16px and 19px ones.

The source of the 16px and 19px ones is `ublock-16px.svg`, while all the rest are rasterized versions of `ublock.svg`. The difference is in the white border and the font weight. The small ones have no borders and a bold font; all of the other ones have a white border and a light weight.

The small changes in `async.js` and `pagestore.js` just removed the extra whitespace.

### CODE REVIEW

**Comment by gorhill** [comment]
We are in subjective territory here. I personally prefer the current ones, and as maintainer of the project, I will keep the current ones.

Actually, it almost looks like you are joking or something: your icons are not even symmetrical, this is obvious to the naked eye. And there was no need to change in color. In any case, like I said, the current ones are fine, I don't intend to change anything.

**Comment by Baegus** [comment]
This is probably the funniest thing I've seen today.

**Comment by CoolOppo** [comment]
The 19px one needs to be fixed due to the hinting though. If I make a pull request to fix it with the current icon, will you take a look at it?

**Comment by CoolOppo** [comment]
Here is a comparison between the current one and another that is properly hinted. The scaled images are scaled up without any interpolation so that you can see exactly how big of a difference it makes.

### Current 19px Icon (Scaled)

Current 19px Icon

### Proposed 19px Icon (Scaled)

Proposed 19px Icon

### Current 19px Icon (Actual Size)



### Proposed 19px Icon (Actual Size)



---

## Edit

This doesn't really belong here, so I made a new issue: #262

**Pull request closed without merging**
