### PR TITLE
Fix for #1122

### PR DESCRIPTION
**Pull request by AlexVallat**
Not sure why busyFlags can be undefined, but through testing it can be, and when it is, it causes #1122

### CODE REVIEW

**Comment by Deathamns** [comment]
This doesn't seem to fix it. As @gorhill mentioned, the problem was that busyFlags had a value of 3, not `undefined`.
If this busyFlags was an issue for Fennec only, then could it be checked only for that?

**Comment by AlexVallat** [comment]
It fixes it for me, tested with Firefox 37 and 39. If you are still reproducing the issue even with this change, perhaps you could investigate further?

I'm not entirely clear on why there has to be a special path for about:blank and about:newtab at all, to be honest - why do those two need to call onNavigation where everything else just calls setIcon?

**Comment by Deathamns** [comment]
I tested with Firefox 29, and latest Nightly. I got 3 for busyFlags.

[About](https://github.com/gorhill/uBlock/commit/263b756764829eebb877f1b5b92bba3da5cf28e0#commitcomment-9450465) `about:blank` [and](https://github.com/gorhill/uBlock/commit/d24263aa1767dee9571b1bf66150acac318e481e) `about:newtab`.

**Comment by AlexVallat** [comment]
It might be worth revisiting that `about:blank` code, then. When I remove any special case and just use:

```
onTabSelect: function({target}) {
        vAPI.setIcon(vAPI.tabs.getTabId(target), getOwnerWindow(target));
        return;
},
```

the popup works perfectly well when clicking the New Tab button.

**Comment by Deathamns** [comment]
That is how it was [before](https://github.com/gorhill/uBlock/commit/d24263aa1767dee9571b1bf66150acac318e481e).
The popup shows up, yes, but `onNavigation` doesn't fire for those `about` pages when a tab is opened (you can see that the toolbar button stays gray).
I'm not sure if it's worth dealing with these cases, because I can't think any scenario which could cause trouble, but to keep this workaround and fix the issue at the same time, checking `busyFlags` only for Fennec would be enough.

**Comment by AlexVallat** [comment]
Well, it's up to you, if you want to just stick in an if vAPI.fennec check in. I still think it would be better to have onTabSelect only call setIcon and never onNavigate, then if the grey icon needs fixing come up with a better workaround elsewhere...

**Comment by AlexVallat** [comment]
Some further investigation: `tabsProgressListener.onLocationChange` doesn't seem to fire for `about:blank`, but interestingly, `webProgressListener` _does_. Which means the stuff we were discussing in #1084 might actually have some tangible benefit after all! Using that branch, together with the simplified `onTabSelect` function, it actually does the job and the icon goes red as expected.

**Comment by Deathamns** [comment]
Alright, let's use `webProgressListener`.

**Comment by AlexVallat** [comment]
Great. I've merged in the webProgressListener branch, and I'll create a new pull request for that one (as this one seems to think there are 58 changed files, which is not right!)

Edit: it is #1135

**Pull request closed without merging**
