### PR TITLE
Goodnight, sweet prince.

### PR DESCRIPTION
**Pull request by ghost**
Thanks for all of your hard work @gorhill and @Deathamns. We greatly
appreciate everything you did. Good luck to @chrisaljoudi.

### CODE REVIEW

**Comment by chrisaljoudi** [comment]
This is incredibly helpful, @hotdogman. Thank you. Will merge momentarily.

**Comment by ghost** [comment]
> Will merge momentarily. 

You might want to review before doing that. It looks like this modified Info.plist for Safari, which might complicate auto-updating and other things. I don't know, I haven't used Safari.

> Thank you.

I'm just glad I was able to do something semi-useful.

For future reference (if needed):
`find * -type f -exec grep -Il . {} \; -exec sed -i 's/old/new/g' {} \;`
`find * -type f -exec grep -Il . {} \; -exec sed -i 's/gorhill/chrisaljoudi/g' {} \;`

**Comment by ajs124** [comment]
On the topic of rebranding: There are still quite some "µ"s in there, most of them in the javascript, but apparently some are also in the translations. See for example [here](https://github.com/chrisaljoudi/uBlock/blob/master/src/_locales/ca/messages.json#L11) or [here](https://github.com/chrisaljoudi/uBlock/blob/master/src/_locales/ja/messages.json#L11).

**Comment by ghost** [comment]
> There are still quite some "µ"s in there

`find * -type f -exec grep -Il . {} \; -exec sed -i 's/µ/u/g' {} \;`
#1073

**Comment by ajs124** [comment]
There are several problems with that approach. First thing, some languages use µ, it's a normal character with a normal usage in them. Second, there are (at least) two Unicode symbols in this codebase that look like this "µ". [The greek letter Mu](http://unicode-table.com/en/03BC/) and [the Micro sign](http://unicode-table.com/en/00B5/).

**Pull request closed without merging**
