### PR TITLE
Corrected links in all locales files

### PR DESCRIPTION
**Pull request by Betsy25**
Corrected "gorhill" with "chrisaljoudi" in all links in locales files.

### CODE REVIEW

**Comment by chrisaljoudi** [comment]
HI @Betsy25!

That looks great — thank you. I notice you closed the pull request; is there an issue?

**Comment by Betsy25** [comment]
Sorry, I thought a pull commit from @muhasturk made this pull invalid.
I'll make a proper pull in a few minutes.

**Comment by chrisaljoudi** [comment]
@Betsy25 no worries — please feel free to take your time.

**Comment by Betsy25** [comment]
@chrisaljoudi I created a correct pull request.
Cheers !

**Pull request closed without merging**
