### PR TITLE
Dynamic Filtering panel

### PR DESCRIPTION
**Pull request by chrisaljoudi**
@gorhill since this changes the dynamic filtering panel, I thought I'd ask you what you thought before merging.

The difference is that the two dynamic filtering columns (which is to say the 2nd and 3rd ones) have been swapped, so now the global filtering column is the "outer" one (closer to the main panel), while the current-site column is the one in the middle.

This is easier to parse visually due to the layout, because it's tempting to want to organize data in one direction from the most generic to the most specific.

To make sure this doesn't silently confuse anyone who's gotten accustomed to the current order **and** to make it clearer for future users, icons have been added:

dynamic filtering panel screenshot

The icons were positioned to align with the columns in the dynamic filtering table. They're on top of a white background, and the combination is subtly translucent to reveal more of the rows in each viewport as the user scrolls (see screencast below).

The icons are a globe and a thumb-tack (sometimes known as a "push pin"). The choices aren't final, but they seem like good candidates. To more clearly communicate the difference in scope, the icons are sized slightly differently to enhance the visual contrast (they are called `scopeIcons` throughout the added code).
##### [Here's a quick screencast testing out the pane](http://cl.ly/aO6F/dfPanel.mp4).<sup>[1]</sup>

So far, this has been tested on the latest Chrome, Firefox, and Safari.
### Footnote

It helps to note that the visual icons don't exclusively rely on the order of the columns — if it's deemed that the original (current) column order is more appropriate, the icons can be integrated while keeping that order.

**[1]** you might've noticed that in the screencast, the `+` and `-`'s in active dynamic filtering cells didn't become white even when their background turned green/red. I pushed the fix (e8d54ac) to this branch, but don't have an updated screencast yet.

### CODE REVIEW

**Comment by TteokbokkiNari** [comment]
Ever since I started using uBlock, I keep thinking the global one is on the right, and local one is on the left like in this pull request, so this would please me. 
The icons and the small white space makes the layout look slightly better, too.

**Comment by gorhill** [comment]
An idea was to put the header in the title bar, as someone suggested on Wilders Security -- somebody made a sketch and I thought this was a good idea (the "uBlock x.x.x.x" would stay exactly where it is when the firewall pane is collapsed). But even then, I wrote prototype code a while ago to see the result and I scrapped it, it felt more like adding noise to me at the time: one just need to read once in the quick guide that the right-most column is the local scope and afterward there is no more need to be reminded about this all the time -- less visual noise.

Aside this, I personally do not see the point of changing anything else for the sake of change at this point, whatever is deemed a gain by changing the order seems quite subjective to me. I am pretty sure most are used now with the current order<sup>[1]</sup> and this to me is more important than debating whether left-to-right or right-to-left works better. This could have been debated early during the design process but now we can't change this, that kind of change will confuse most users out there.

[1] order which I picked originally because of many reasons: I see left-to-right as broadest-to-narrowest, just like I read numbers, also, the local scope is typically the most-used one so to have it closer to the toolbar icon means having to travel less with the mouse. It is small details but this is these which helps me make decisions when it all appears arbitrary.

**Comment by gorhill** [comment]
The scrollbar in the video... how come it is positioned away from the edge of the popup?

**Comment by chrisaljoudi** [comment]
@gorhill I have no idea, but it's not caused by any changes in the `dfPane` branch. 

It's specific to Chromium on OS X (OS X has different conventions for how scrollbars are rendered — they're not allocated width, and they're invisible at all times except for when you're scrolling). 

Not only is not caused by the dfPane branch, but the behavior is reproducible with uBlock builds as old as I can bother to test. Will look into it.

**Comment by chrisaljoudi** [comment]
@gorhill do you think we should integrate the addition of the icons (while keeping the column order the same) or keep things completely as-is?

**Comment by gorhill** [comment]
> do you think we should integrate the addition of the icons

As said, I did try headers in the past (not icons though), and given that I know what each column are for, this was visual noise to me. Now the first time you still see the pane, this maybe help _if_ these icons come with their tooltip, but the quick guide is a required reading anyways, and I can't imagine an advanced user having a hard time to remember the purpose of each column. Adding to this that clicking on a cell give a good hint of what is global/local -- global cells will bleed into their local counterpart. In short, I prefer to leave it the current way.

> Will look into it.

I was just curious. So it's an OS X thing, I just wish I had that kind of scroll bars, they get out of the way when not used -- though we lose the sense of how many rows there are in total.

Cursious again: what is the resolution of your screen? The images you post always look very sharp.

**Comment by my-password-is-password** [comment]
@gorhill About the scrollbars.  Why now use css to make the scrollbars smaller.  Heres how I have it.

ublockthinscrollbars

Here are the changes to popup.css.
https://github.com/my-password-is-password/stuff/blob/master/uBlock.Chromium_thinScrollbar.zip

**Comment by chrisaljoudi** [comment]
@my-password-is-password yeah — the thing is, styling scrollbars is asking for trouble in general, especially if you do this in the core CSS for uBlock (vs. something platform-specific).

Browser support is flakey, inconsistent, and overall a pain in the butt.

I'm not against what you've illustrated/achieved _at all_ — I hope you understand I'm merely concerned about problems arising from browser implementations.

---

The advantage of going with native scrollbars is that is makes it much easier to get reasonable native-feeling results on an arbitrary number of platforms.

**Comment by my-password-is-password** [comment]
@chrisaljoudi Yeah, i understand.  Not asking to include it in uBlock but just a suggestion for gorhill to change his local copy to something he likes by changing css.

**Comment by gorhill** [comment]
I looked in the past at scroll bar stuff, and I rely on MDN doc to figure whether something can be used safely or not, and scrollbar UI is not among those things which can be dealt with safely across platforms.

**Comment by chrisaljoudi** [comment]
Seems like we can close this.

**Pull request closed without merging**
