### PR TITLE
Turkish Translation Update

### PR DESCRIPTION
**Pull request by ghost**
I am a new user of uBlock for Opera. I want to see this extension my language. So I updated this Turkish language file.
Please add this into next update. Thanks

### CODE REVIEW

**Comment by gorhill** [comment]
Thanks!

**Comment by gorhill** [comment]
> Please add this into next update

I forgot to mention that the Opera store won't accept the Turkish version if the [description](https://crowdin.com/project/ublock/tr) is not also available (the Chrome store they don't mind if the description is not available).

**Comment by ghost** [comment]
I translated all strings in Crowdin with my account. You can check here : https://crowdin.com/project/ublock/tr 
if there are more strings to translate please inform me. I did my best on Crowdin, you can use it just now. It is as good as perfect :)

**Comment by gorhill** [comment]
Got it, thanks. I will cancel previous submission and resubmit to Opera so that the next version has the translation.

**Comment by ghost** [comment]
Updated to next version and translations works on new version. When it will be released on Chrome Web Store ?

**Comment by gorhill** [comment]
The extension on Chrome web store has been in "pending review" mode for over a week now. Details in the release log with me speculating why it's happening: https://github.com/gorhill/uBlock/releases/tag/0.5.0.1.

**Comment by ghost** [comment]
Do you have a plan about realesing a Firefox based version of uBlock ? I am using Cyberfox that based on firefox source code
Thanks for the information

**Comment by gorhill** [comment]
That is issue #27. The TL;DR is that there is so much one coder can do, another developer will need to pick up the work there, and in such case I will work closely to identify/extract a common code core between both extensions.

**Comment by gorhill** [comment]
Another contributor is revising your translations on Crowdin. Can you guys agree on what is best? I can't be the one deciding.

**Pull request merged**
