### PR TITLE
Set up Travis releases.

### PR DESCRIPTION
**Pull request by fwalch**
You can find the documentation of this feature [here](http://docs.travis-ci.com/user/deployment/releases/). Basically, it would automatically publish XPI (Firefox) and ZIP (Chromium) to a Github release when you create a tag on your repo.
#### What it does

Here's an overview of how it works: I created a test tag `0.8.5.4-TEST` and pushed it. This triggered a [build](https://travis-ci.org/fwalch/uBlock/builds/46956853), which in turn created a release at https://github.com/fwalch/uBlock/releases/tag/0.8.5.4-TEST. As you can see, this has the two files for Firefox and Chromium. The commit message of the tagged commit is used as the release description, but you can also edit that later.

For ordinary commits (i.e. non-tagged), it of course doesn't create a release. See e.g. [this build](https://travis-ci.org/fwalch/uBlock/jobs/46954518#L102).
#### Required steps

If you want to merge this, I think the easiest way is the following (unfortunately it's still a bit lengthy, at least if you never used Travis):
1. Create Travis account:
   1. Go to https://travis-ci.org and log in with Github.
2. Generate a Github token that allows Travis to create new releases at Github:
   1. Install the `travis` Ruby gem (`gem install travis`)
   2. Change to the uBlock directory and execute `travis setup releases`. You'll need to log in with your Github username and password. What you answer is not that important, only that you say "yes" when it asks "Encrypt API key?". Copy the value of `api_key.secure` of generated `.travis.yml` somewhere for later.
   3. Remove the `.travis.yml`.
3. Merge this PR and replace `TODO: your key here!` in the `travis.yml` with the encrypted key you got in step 2.2 (similar to https://github.com/fwalch/uBlock/commit/f160ddfba8d888bea58492786f98b6fe4d264dd2).
4. Go to your profile page at https://travis-ci.org/profile and enable Travis for the `gorhill/uBlock` repository.

The next time you push a tag, Chromium and XPI files will automatically be added to a new release.

I hope you find this useful; if you have any questions, let me know!

### CODE REVIEW

**Comment by gorhill** [comment]
Looks nice, thanks. That will save time.

**Comment by gorhill** [comment]
When I look up `gem`, I am told if can be found in two packages: `ruby` and `rubygems`. Which one should I install (the smallest for all this to work)?

**Comment by fwalch** [comment]
Hm, `rubygems`, I guess.. which OS are you on?

**Comment by gorhill** [comment]
Linux Mint.

**Comment by fwalch** [comment]
Well, you can install `ruby` and see if it has the `gem` executable (on my OS, this is the case [Arch Linux]). If not, `rubygems` will probably depend on `ruby` anyway.

**Pull request merged**
