### PR TITLE
Inline CSS → embedded CSS (except `display: none`)

### PR DESCRIPTION
**Pull request by Zearin**
If this works for you, I can do more. :)

Thanks for uBlock!

### CODE REVIEW

**Comment by Zearin** [comment]
> Values in attribute selectors should be quoted: [data-i18n="3pExternalListsHint"]

I’d forgotten that!  Will fix shortly.

> (Also, that's a digit 1 in the markup, not a lowercase L: i18n is a common abbreviation for "internationalization" because there are 18 characters between i and n; similarly, l10n means "localization")

Ah okay.  That makes more sense.  I thought it was “l8n” for “localization” and “i8n” for “internationalization” because the “8” sounds kind of like the “-za-” part of both words.  (I thought it was kinda dumb, but that’s what I figured.  Looks like I turned out to be the dumb one! :p)

Will fix this shortly, too.

**Comment by Zearin** [comment]
(Sorry this took me a while to get back to!)

The issues have been fixed, and I’ve rebased my changes onto your latest master.

**Comment by Gitoffthelawn** [comment]
Hard-coded font sizes do not work for accessibility purposes.  Users who use larger default font sizes will not have properly sized fonts.  In CSS, percentages and values such as "small" and "large" allow accessible use.

**Comment by Zearin** [comment]
> Hard-coded font sizes do not work for accessibility purposes. Users who use larger default font sizes will not have properly sized fonts. In CSS, percentages and values such as "small" and "large" allow accessible use.

Oh, I strongly agree!  I actually intended to propose this in a future Pull Request.  The only reason I didn’t is because I wanted my first PR to this project to stay small and focused on one thing: making inline styles embedded (except for `display: none`, which I assume interacts with controller scripts, so I didn’t want to potentially break those).

I will gladly update the font sizes shortly!

**Comment by Zearin** [comment]
@Gitoffthelawn Okay, `13px` is now `small`.

After this PR is done, I can continue making more small updates, if you wish.

**Comment by Gitoffthelawn** [comment]
AFAIK, uBlock is open to the whole world to make contributions!

BTW, why is it better to make the styles embedded?

**Pull request closed without merging**
