### PR TITLE
Render icons with better font hinting

### PR DESCRIPTION
**Pull request by CoolOppo**
It's extremely subtle, but it'll make the icons look _slightly_ better.

If anybody's interested, see [Wikipedia's explanation of font hinting](https://en.wikipedia.org/wiki/Font_hinting) for more info.

### CODE REVIEW

**Comment by chrisaljoudi** [comment]
Hi @CoolOppo!

Thanks for that. The only thing is, your render of `icon38@2x.png` appears to be `78x78` instead of `76x76`.

Other than that, looks great. Thanks again.

**Comment by CoolOppo** [comment]
My bad; I'll fix that right now.

**Comment by CoolOppo** [comment]
Okay, it's fixed! Sorry for that. Good thing you were paying attention because I obviously was not.

**Comment by CoolOppo** [comment]
Wait a second: the old version of `icon64@2x.png` was definitely better. All the other ones I changed are totally alright, but that one actually is blurrier after my change. I'll fix that.

~~Edit: hold off on merging still. I'm not quite happy with it.~~

**Comment by CoolOppo** [comment]
Alright, I am finally happy with these icons! Go ahead and merge if you like.

**Pull request merged**
