### PR TITLE
add yandex to mirror candidates

### PR DESCRIPTION
**Pull request by rlex**
This CDN is widely used in russia.
Some description (russian only, sorry): https://tech.yandex.ru/jslibs/

### CODE REVIEW

**Comment by rlex** [comment]
Oh, it also appears yandex itself use yastatic.net as their own CDN, not only for JS hosting. Should i add entries as yastatic.net/angular, yastatic.net/jquery and etc?

**Comment by gorhill** [comment]
It's what I am looking at. We need to be careful to not be too broad so as to include everything. I was about to suggest to change the regex to

```
^yastatic\.net\/.+\.js$
```

You think that would still be too broad?

For `yandex.st`, I want to have some reference pages to understand what this would end up including. For the time being, I don't want to include this broad candidate until we understand what it would end up including.

The space allocated to mirroring is limited, so we want to be sure only things which have a good probability of being reused are mirrored.

**Comment by gorhill** [comment]
Actually, to be on the safer side, yes, it would be better to be more explicit with the regex to include only what is listed on the page. A non-capturing group should be used:

```
^yastatic\.net\/(?:angularjs|backbone|bootstrap|...)\/
```

**Comment by rlex** [comment]
i can assure it's very widely used on russian websites. There is page i linked with list of JS libraries they're hosting. 
Including all JS libs may do the trick, i briefly checked their services and found no custom JS libs, but i may be wrong.
As example for popularity: http://www.alexa.com/siteinfo/yandex.st http://www.alexa.com/siteinfo/yastatic.net

**Comment by rlex** [comment]
Yeah, that way it will be better.
Should i squash my previous commit or i can just add new on top of previous?

**Comment by gorhill** [comment]
Just add on top, so we keep the thread here.

**Comment by rlex** [comment]
Added. Maybe should be with *.js as well, but it also hosts some CSS (for example, bootstrap default CSS)

**Comment by gorhill** [comment]
Could you re-submit the same changes for `assets/ublock/mirror-candidates.txt`. The `assets` in `src` is not used, I need to delete it.

**Pull request merged**
