### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by jeffehobbs**
Fixed typo ("criminalization").

### CODE REVIEW

**Comment by chrisaljoudi** [comment]
What's the typo?

**Comment by jeffehobbs** [comment]
criminalisation vs. criminalization. 

And now as I look into this more: it's a regional thing? Sorry, probably not a typo actually. Seems to be a difference in regional spelling, ala color v. colour.

http://en.wikipedia.org/wiki/Criminalization

**Comment by chrisaljoudi** [comment]
@jeffehobbs oh, yep; it is.

**Comment by gorhill** [comment]
Dup of #448.

**Pull request closed without merging**
